[licenses]
copyleft = "allow"
allow = [ "Apache-2.0", "MIT", "Unlicense" ]

[advisories]
# this one has no real workaround. However, it only occurs if we modify a specific environment variable
# in a multi-threaded setup.
ignore = ["RUSTSEC-2020-0159"]
